<?php
 
 $apps=array(
 	'libraries'=>array(
 	 		'path'=>'libraries',
 	 		'title'=>'类库',
 	 		'index'=>'',
 	 		'readme'=>'README.md',
 	 ),
 	'searchselect'=>array(
 	 		'path'=>'searchSelect',
 	 		'title'=>'可输入可搜索下拉框',
 	 		'index'=>'',
 	 		'readme'=>'README.md',
 	 ), 
 	'cookies'=>array(
 	 		'path'=>'cookie',
 	 		'title'=>'cookie测试',
 	 		'index'=>'',
 	 		'readme'=>'README.md',
 	 ), 
 	'restful'=>array(
 	 		'path'=>'restfulApi',
 	 		'title'=>'REST Api',
 	 		'index'=>'',
 	 		'readme'=>'README.md',
 	 ), 
 	'booktest'=>array(
 	 		'path'=>'booktest',
 	 		'title'=>'图书增删例子',
 	 		'index'=>'',
 	 		'readme'=>'README.md',
 	 ), 
 	'capture'=>array(
 	 		'path'=>'capture',
 	 		'title'=>'数据抓取',
 	 		'index'=>'scrwal.php',
 	 		'readme'=>'README.md',
 	 ), 
 	'tools'=>array(
 	 		'path'=>'tools',
 	 		'title'=>'小工具',
 	 		'index'=>'',
 	 		'readme'=>'README.md',
 	 ), 
 	'excel'=>array(
 	 		'path'=>'excel',
 	 		'title'=>'excel 读取',
 	 		'index'=>'',
 	 		'readme'=>'README.md',
 	 ),  
 	'slimapi'=>array(
 	 		'path'=>'slimapi',
 	 		'title'=>'slim 框架例子',
 	 		'index'=>'',
 	 		'readme'=>'README.md',
 	 ), 
 	'excels'=>array(
 	 		'path'=>'excels',
 	 		'title'=>'excels',
 	 		'index'=>'',
 	 		'readme'=>'README.md',
 	 ),  
 	'faker'=>array(
 	 		'path'=>'faker',
 	 		'title'=>'faker',
 	 		'index'=>'faker.php',
 	 		'readme'=>'README.md',
 	 ), 
 );